name: build pdf

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'pre-release-v0.0.1'

jobs:
  build:
    name: build pdf and upload release
    runs-on: ubuntu-24.04
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0  # optional semver specification, otherwise latest

      # Install dependencies
      - name: Install dependencies
        working-directory: ./docs
        run: |
          just install-deps-ci

      # Build PDFs
      - name: Build pdf for all languages
        working-directory: ./docs
        run: |
          # To skip confirmation prompts, use --yes
          just --yes build-pdf-all

      # If event is a tag, use the tag
      # Else if the event is workflow_dispatch, use the input tag_name
      - name: Specify the tag and release name
        id: specify_tag_name
        run: |
          set -eof pipefail
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag_name=${{ github.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "No tag name specified"
            exit 1
          fi

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.specify_tag_name.outputs.tag_name }}
          release_name: Release ${{ steps.specify_tag_name.outputs.tag_name }}
          draft: false
          prerelease: false
      - name: upload Release Asset en
        id: upload-release-asset-en
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs/out/RESUME.en.pdf
          asset_name: RESUME.en.pdf
          asset_content_type: application/pdf
      - name: upload Release Asset jp
        id: upload-release-asset-jp
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs/out/RESUME.jp.pdf
          asset_name: RESUME.jp.pdf
          asset_content_type: application/pdf
