name: build pdf

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'pre-release-v0.0.1'

jobs:
  build:
    name: build pdf and upload release
    runs-on: ubuntu-24.04
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0  # optional semver specification, otherwise latest

      # Install dependencies
      - name: Install dependencies
        working-directory: ./docs
        run: |
          just install-deps-ci

      # Build PDFs
      - name: Build pdf for all languages
        working-directory: ./docs
        run: |
          # To skip confirmation prompts, use --yes
          # With ci=true to launch puppeteer without a sandbox
          just --yes build-pdf-all true

      # Determine tag
      # If event is a tag, use the tag
      # Else if the event is workflow_dispatch, use the input tag_name
      - name: Specify the tag and release name
        id: specify_tag_name
        run: |
          set -eof pipefail
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_NAME="${GITHUB_REF##*/}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG_NAME="${{ github.event.inputs.tag_name }}"
          else
            echo "No tag name specified"
            exit 1
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      # Create release and upload assets
      - name: Create GitHub release and upload PDFs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.specify_tag_name.outputs.tag_name }}
          name: Release ${{ steps.specify_tag_name.outputs.tag_name }}
          files: |
            ./docs/out/RESUME.en.pdf
            ./docs/out/RESUME.jp.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
